<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\DocumentMDConverter.Application\DocumentMDConverter.Application.csproj" />
    <ProjectReference Include="..\DocumentMDConverter.Infrastructure\DocumentMDConverter.Infrastructure.csproj" />
    <ProjectReference Include="..\DocumentMDConverter.Domain\DocumentMDConverter.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Dockerfile" />
  </ItemGroup>

  <PropertyGroup>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

</Project>
