<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DocumentMDConverter.Domain\DocumentMDConverter.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Markdig" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

</Project>
